### PR TITLE
Treat selections in "contenteditable" elements like those in input and textarea elements

### PR DESCRIPTION
**Pull request by bijancamp**
Hi Per! I came across an edge case that I thought could be handled by this change.

Currently, when text is selected in certain rich-text areas (elements that have the "contenteditable" attribute set to true), Selection Search acts as if the selection is not in an editable region. Specifically, if the Auto activator is being used, the popup button is shown automatically when text is selected in these elements. Here is an example of selecting text in such a region on [twitter.com](https://twitter.com/):

illustration of selection search in contenteditable elements

Similar behavior occurs when using the "Mouse Click" activator.

This behavior can be an issue when double clicking or triple clicking text inside one of these regions: the popup button (if using the Auto activator) or menu (if using the Mouse Click activator) will automatically open, making it easier for the user to accidentally click a search engine. This change makes selections in contenteditable elements act the same as selections in input or textarea elements. :)

I am still a newbie JS developer, so I hope this change makes sense. Please let me know if you would like me to make some more changes. :)

### CODE REVIEW

**Comment by Pitmairen** [comment]
Hi, thank you. This is probably the correct behavior to make it consistent with other input/textarea.

I have merged your pull request, but I did some cleanup on the history to remove unnecessary commits to keep the log clean. Only the last commit which did the real change was kept.

**Comment by Pitmairen** [comment]
Merged in f6b61068211a75b20ead990bddd38100aa5f323a

**Comment by bijancamp** [comment]
Thank you for the merge and clean up, Per! And thank you for this wonderful extension! :D I am looking forward to learning more about git and JS so I can contribute more. ;)

**Comment by Pitmairen** [comment]
That's great! :) I will release a new version soon, but I need to fix a few things first.

**Comment by bijancamp** [comment]
Thank you! I am looking forward to it. :D

**Pull request closed without merging**
